name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gargp2/nginx-9000
          tags: ${{ github.run_number }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: modify the image tag
        working-directory: manifests
        run: |
          pwd
          cat nginx.yaml
          pwd
          sed -i "s+gargp2/nginx-9000.*+gargp2/nginx-9000:${{ github.run_number }}+g" nginx.yaml
          cat nginx.yaml
          git add .
          git commit -m 'Updated  by Github Actions: Job changemanifest: ${{ github.run_number }}'
          git push origin main
